lvgl:
  pages:
    - id: canvas_1
      bg_color: 0x111827
      widgets:
        - tabview:
            id: lv_tabview_7
            x: 0
            y: 0
            width: 320
            height: 172
            size: 17%
            bg_color: 0x1F2937
            tabs:
              - name: Battery
                widgets:
                  - label:
                      id: lv_label_soc
                      x: 0
                      y: 0
                      width: 155
                      height: 70
                      text: "100%"
                      text_color: 0x03FC35
                      text_align: CENTER
                      text_font: montserrat_48
                  - label:
                      id: lv_label_current
                      x: 0
                      y: 75
                      width: 155
                      height: 60
                      text: "+20.3 A"
                      text_color: 0xF83516
                      text_align: CENTER
                      text_font: montserrat_36
                  - label:
                      id: lv_label_time_to_fullempty
                      x: 165
                      y: 5
                      width: 150
                      height: 30
                      text: "Time to full:"
                      text_color: 0x707070
                      text_align: CENTER
                      text_font: montserrat_18
                  - line:
                      id: lv_line_13
                      x: 150
                      y: 0
                      width: 10
                      height: 140
                      points:
                        - 5, 5
                        - 5, 135
                      line_width: 3
                      line_color: 0x376E95
                  - label:
                      id: lv_label_time_to_fullempty_hhmm
                      x: 165
                      y: 35
                      width: 150
                      height: 30
                      text: "122d 12h 23m"
                      text_align: CENTER
                      text_font: montserrat_20
              - name: Info
                widgets:
                  - textarea:
                      id: lv_textarea_info_text
                      x: 0
                      y: 0
                      width: 314
                      height: 137
                      text: |-
                        Uptime: 211d 4h 12m 02s
                        IP: disconnected
                        Cell Voltages (mV): 3326 3325 3322 3323
                        Total Voltage: 13.2V
                        Battery Cycles: 21
                        MQTT: connected
                        Temperature: 21.2C
              - name: Settings
                widgets:
                  - label:
                      id: lv_label_16
                      x: 0
                      y: 0
                      width: 180
                      height: 30
                      text: "Charge limiter active"
                      text_font: montserrat_16
                  - switch:
                      id: lv_switch_limiter_active
                      x: 180
                      y: 0
                      width: 60
                      height: 30
                      bg_color: 0x4B5563
                      indicator:
                        bg_color: 0x4F46E5
                      knob:
                        bg_color: 0xFFFFFF
                        border_color: 0x9CA3AF
                        border_width: 1
                  - dropdown:
                      id: lv_dropdown_limiter_soc
                      x: 240
                      y: 0
                      width: 70
                      height: 30
                      options:
                        - "100%"
                        - "90%"
                        - "80%"
                      selected_index: 1
                  - label:
                      id: lv_label_15
                      x: 0
                      y: 35
                      width: 180
                      height: 30
                      text: "Charge enabled"
                      text_font: montserrat_16
                  - switch:
                      id: lv_switch_23
                      x: 180
                      y: 35
                      width: 60
                      height: 30
                      bg_color: 0x4B5563
                      indicator:
                        bg_color: 0x4F46E5
                      knob:
                        bg_color: 0xFFFFFF
                        border_color: 0x9CA3AF
                        border_width: 1
                  - label:
                      id: lv_label_24
                      x: 0
                      y: 70
                      width: 180
                      height: 30
                      text: "Discharge enabled"
                      text_font: montserrat_16
                  - switch:
                      id: lv_switch_25
                      x: 180
                      y: 70
                      width: 60
                      height: 30
                      bg_color: 0x4B5563
                      indicator:
                        bg_color: 0x4F46E5
                      knob:
                        bg_color: 0xFFFFFF
                        border_color: 0x9CA3AF
                        border_width: 1
                  - slider:
                      id: lv_slider_28
                      x: 105
                      y: 110
                      width: 200
                      height: 20
                      value: 63
                      min_value: 0
                      max_value: 100
                      bg_color: 0x374151
                      knob:
                        bg_color: 0xFFFFFF
                        border_color: 0x4F46E5
                        border_width: 2
                      indicator:
                        bg_color: 0x4F46E5
                  - label:
                      id: lv_label_27
                      x: 0
                      y: 105
                      width: 100
                      height: 30
                      text: "Backlight"
                      text_font: montserrat_16
