[env:waveshare-esp32-c6-lcd]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_size  = 8MB
board_build.partitions  = default_8MB.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DLV_CONF_INCLUDE_SIMPLE=1
    -I${PROJECT_DIR}/include
    -I$PROJECT_LIBDEPS_DIR/$PIOENV/lvgl/src
    -DESP_LCD_TOUCH_IO_I2C
    -UCONFIG_ARDUINO_LOOP_STACK_SIZE
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
    knolleary/PubSubClient @ ^2.8
    #moononournation/GFX Library for Arduino @ ^1.4.9
    h2zero/NimBLE-Arduino @ ^2.3.9
    lvgl/lvgl @ ^8.3.0
    Wire

board_build.sdkconfig = sdkconfig.defaults